name: Android CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

  test:
    needs: build  # Run this job only if the build job succeeds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Run tests
        run: ./gradlew test

  notify:
    needs: test  # Run this job only if the test job succeeds
    if: failure()  # Only run if the previous job fails
    runs-on: ubuntu-latest
    steps:
      - name: Send email on failure
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}  # Replace with your email username
          password: ${{ secrets.EMAIL_PASSWORD }}  # Replace with your email password
          subject: Build failed on ${{ github.ref }}
          body: |
            Build failed for ${{ github.workflow }} on ${{ github.ref }}.
            See the build log here: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          recipient: ${{ github.actor }}  # Email address of the commit author
